# Generated by Django 4.2 on 2023-04-19 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0003_match'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Poule',
            new_name='Pool',
        ),
        migrations.RenameModel(
            old_name='Equipe',
            new_name='Team',
        ),
        migrations.RenameModel(
            old_name='Tournoi',
            new_name='Tournament',
        ),
        migrations.AlterModelTable(
            name='pool',
            table='tournaments_poule',
        ),
        migrations.AlterModelTable(
            name='team',
            table='tournaments_equipe',
        ),
        migrations.AlterModelTable(
            name='tournament',
            table='tournaments_tournoi',
        ),
    ]
