# Generated by Django 4.2 on 2023-04-19 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0004_rename_poule_pool_rename_equipe_team_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pool',
            name='conceded',
            field=models.IntegerField(null=True, verbose_name='Number of goals conceded'),
        ),
        migrations.AddField(
            model_name='pool',
            name='pool_points',
            field=models.IntegerField(null=True, verbose_name='Number of pool points'),
        ),
        migrations.AddField(
            model_name='pool',
            name='scored',
            field=models.IntegerField(null=True, verbose_name='Number of goals scored'),
        ),
    ]
