# Generated by Django 4.2 on 2023-04-19 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0005_pool_conceded_pool_pool_points_pool_scored'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pool',
            name='conceded',
            field=models.IntegerField(default=0, null=True, verbose_name='Number of goals conceded'),
        ),
        migrations.AlterField(
            model_name='pool',
            name='pool_points',
            field=models.IntegerField(default=0, null=True, verbose_name='Number of pool points'),
        ),
        migrations.AlterField(
            model_name='pool',
            name='scored',
            field=models.IntegerField(default=0, null=True, verbose_name='Number of goals scored'),
        ),
    ]
