# Generated by Django 4.2 on 2023-04-19 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0006_alter_pool_conceded_alter_pool_pool_points_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pool',
            name='conceded',
        ),
        migrations.RemoveField(
            model_name='pool',
            name='pool_points',
        ),
        migrations.RemoveField(
            model_name='pool',
            name='scored',
        ),
        migrations.AddField(
            model_name='team',
            name='conceded',
            field=models.IntegerField(default=0, null=True, verbose_name='Number of goals conceded'),
        ),
        migrations.AddField(
            model_name='team',
            name='pool_points',
            field=models.IntegerField(default=0, null=True, verbose_name='Number of pool points'),
        ),
        migrations.AddField(
            model_name='team',
            name='scored',
            field=models.IntegerField(default=0, null=True, verbose_name='Number of goals scored'),
        ),
    ]
