# Generated by Django 4.2 on 2023-04-19 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0007_remove_pool_conceded_remove_pool_pool_points_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='conceded',
            field=models.IntegerField(null=True, verbose_name='Number of goals conceded'),
        ),
        migrations.AlterField(
            model_name='team',
            name='pool_points',
            field=models.IntegerField(null=True, verbose_name='Number of pool points'),
        ),
        migrations.AlterField(
            model_name='team',
            name='scored',
            field=models.IntegerField(null=True, verbose_name='Number of goals scored'),
        ),
    ]
