# Generated by Django 4.2 on 2023-04-19 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0008_alter_team_conceded_alter_team_pool_points_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=200)),
                ('hour', models.CharField(max_length=200)),
                ('message', models.CharField(max_length=600)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournaments.match')),
            ],
        ),
    ]
