# Generated by Django 4.2 on 2023-04-20 14:35

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0009_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='date',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='hour',
        ),
        migrations.AddField(
            model_name='comment',
            name='pub_date',
            field=models.DateTimeField(null=True, verbose_name='Date & hour published'),
        ),
    ]