# Generated by Django 4.2 on 2023-04-22 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0010_remove_comment_date_remove_comment_hour_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matches', models.ManyToManyField(to='tournaments.match')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournaments.tournament')),
            ],
            options={
                'db_table': 'tournaments_finalround',
            },
        ),
    ]
