# Generated by Django 4.2 on 2023-05-03 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0012_alter_place_latitude_alter_place_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='localisation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tournaments.place'),
        ),
    ]
