# Generated by Django 4.2 on 2023-04-26 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0012_alter_match_pool'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalround',
            name='rounds',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='match',
            name='round',
            field=models.IntegerField(null=True),
        ),
    ]
