# Generated by Django 4.2 on 2023-05-01 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0013_finalround_rounds_match_round'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalround',
            name='total_first_round_matches',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='match',
            unique_together={('team1', 'team2', 'round')},
        ),
    ]
