# Generated by Django 4.2 on 2023-05-03 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0013_finalround_rounds_match_round'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalround',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournaments.tournament', unique=True),
        ),
    ]
