# Generated by Django 4.2 on 2023-05-02 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0013_finalround_rounds_match_round'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='played',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='match',
            unique_together={('team1', 'team2', 'round')},
        ),
    ]
