# Generated by Django 4.2 on 2023-05-02 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0013_finalround_rounds_match_round'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='match',
            unique_together={('team1', 'team2', 'round')},
        ),
    ]
