# Generated by Django 4.2 on 2023-05-03 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0014_alter_finalround_tournament'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalround',
            name='tournament',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tournaments.tournament'),
        ),
    ]
