# Generated by Django 4.2 on 2023-05-02 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0014_match_played_alter_match_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='played',
        ),
    ]
