# Generated by Django 4.2 on 2023-05-03 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0015_alter_finalround_tournament'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='round',
        ),
    ]
