# Generated by Django 4.2 on 2023-05-03 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0013_match_localisation'),
        ('tournaments', '0017_match_round'),
    ]

    operations = [
    ]
