# Generated by Django 4.2 on 2023-05-03 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0019_match_tournament_alter_match_pool'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='pool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournaments.pool'),
        ),
        migrations.AlterField(
            model_name='match',
            name='tournament',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='tournaments.tournament'),
        ),
    ]
