# Generated by Django 4.2 on 2023-05-03 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0020_alter_match_pool_alter_match_tournament'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='tournament',
        ),
    ]
