# Generated by Django 4.2 on 2023-05-04 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0020_alter_match_pool'),
    ]

    operations = [
        migrations.RunSQL('ALTER TABLE new__tournaments_match DROP COLUMN pool_id;'),
    ]
