# Generated by Django 4.2 on 2023-05-04 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0020_alter_match_pool'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='date',
            field=models.DateField(null=True, verbose_name='Date of the tournament'),
        ),
        migrations.AlterField(
            model_name='match',
            name='pool',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tournaments.pool'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='date',
            field=models.DateField(null=True, verbose_name='Date of the tournament'),
        ),
    ]
